# Generated by Django 4.2.16 on 2024-09-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_user_username_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
